name: kristinas_daily
description: Kristina's Daily App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.6.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_picker_windows: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/stickers/
